CREATE TABLE TB_CLIENTE
(
	CLI_ID		INTEGER		 NOT NULL,	
	CLI_NOME	VARCHAR2(100) NOT NULL,	
	CLI_UF		VARCHAR2(2)	NULL,
	CLI_Celular	VARCHAR2(15) NULL
);

ALTER TABLE TB_CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CLI_ID);

CREATE TABLE TB_FINANCIAMENTO
(
    FIN_ID      INTEGER  NOT NULL,
    FIN_TIPO    INTEGER NOT NULL,
    FIN_VALORTOTAL NUMBER(10, 2) NOT NULL,
    FIN_DATAVENCIMENTO DATE NOT NULL,
    FIN_CLI_ID INTEGER NOT NULL
);

ALTER TABLE TB_FINANCIAMENTO ADD CONSTRAINT PK_FINANCIMENTO PRIMARY KEY(FIN_ID);
ALTER TABLE TB_FINANCIAMENTO ADD CONSTRAINT FK_CLIENTE_FINANCIAMENTO FOREIGN KEY (FIN_CLI_ID) REFERENCES TB_CLIENTE (CLI_ID);

CREATE TABLE TB_PARCELA
(
    PAR_ID  INTEGER NOT NULL,
    PAR_FIN_ID  INTEGER NOT NULL,
    PAR_Numero  INTEGER NOT NULL,
    PAR_VALOR   NUMBER(10, 2) NOT NULL,
    PAR_DATAVENCIMENTO  DATE NOT NULL,
    PAR_DATAPAGAMENTO DATE  NULL
);

ALTER TABLE TB_PARCELA ADD CONSTRAINT PK_PARCELA PRIMARY KEY (PAR_ID);
ALTER TABLE TB_PARCELA ADD CONSTRAINT FK_PARCELA_FINANCIAMENTO FOREIGN KEY (PAR_FIN_ID) REFERENCES TB_FINANCIAMENTO (FIN_ID);







