
-- Listar todos os clientes do estado de SP que tenham mais de 60% das parcelas pagas
SELECT C.CLI_NOME, COUNT(PP.PAR_ID) * 100 / COUNT(PT.PAR_ID) PERCENTUAL_PAGO
FROM TB_CLIENTE C 
INNER JOIN TB_FINANCIAMENTO F ON C.CLI_ID = F.FIN_CLI_ID
INNER JOIN TB_PARCELA PT ON F.FIN_ID = PT.PAR_FIN_ID
LEFT OUTER JOIN (SELECT * FROM TB_PARCELA P WHERE P.PAR_DATAPAGAMENTO IS NOT NULL) PP ON F.FIN_ID = PP.PAR_FIN_ID AND PT.PAR_ID = PP.PAR_ID
GROUP BY C.CLI_NOME
HAVING COUNT(PP.PAR_ID) * 100 / COUNT(PT.PAR_ID) > 60

-- LISTAGEM DOS 4 PRIMEIROS CLIENTES QUE ESTÃO COM AS PARCELAS ATRASADAS EM MAIS DE 5 DIAS 
-- Listar os primeiros 4 clientes que tenham alguma parcela com mais de 05 dias atrasadas (Data Vencimento maior que data atual E data pagamento nula)

SELECT * FROM TB_CLIENTE C 
INNER JOIN TB_FINANCIAMENTO F ON C.CLI_ID = F.FIN_CLI_ID
INNER JOIN TB_PARCELA P ON F.FIN_ID = P.PAR_FIN_ID
WHERE P.PAR_DATAVENCIMENTO < SYSDATE - 5
AND P.PAR_DATAPAGAMENTO IS NULL
AND ROWNUM < 5;

-- LISTAGEM DE TODOS OS CLIENTES QUE JÁ ATRASARAM A PARCELA EM MAIS DE 10 DIAS
-- Listar todos os clientes que já atrasaram em algum momento duas ou mais parcelas em mais de 10 dias, e que o valor do financiamento seja maior que R$10.000,00
SELECT DISTINCT(C.CLI_NOME) FROM TB_CLIENTE C 
INNER JOIN TB_FINANCIAMENTO F ON C.CLI_ID = F.FIN_CLI_ID
INNER JOIN TB_PARCELA P ON F.FIN_ID = P.PAR_FIN_ID
WHERE (P.PAR_DATAPAGAMENTO - P.PAR_DATAVENCIMENTO) > 10
AND F.FIN_VALORTOTAL > 10000